#' @keywords internal
#' Delclares a function that will be implemented to access data for a single KIR allele after parsing.
#' Initially this allele lives within a 'dict_Python' object. This function will be implemented to
#' extract the data from the pyhton object and provides it as a simple list in R.
setGeneric(name = "getAlleleList", def = function(dictPy, ...) {
  standardGeneric("getAlleleList")
})

#' @keywords internal
#' Declares a function that will expect the output from a database parser. The current implementation takes a PythonDB-object,
#' which is generated by the parser. The function returns a KIRAlleleList.
setGeneric(name = "getAllelesFromPython", def = function(db, ...) {
  standardGeneric("getAllelesFromPython")
})

#' @keywords internal
#' This declares an extractor method to pull alleles from a KIRAlleleList, which are entries for one particular KIR gene.
setGeneric(name = "getKIRGene", def = function(kil, ...) {
  standardGeneric("getKIRGene")
})

#' @keywords internal
#' Declare extractor to pull gene names from a KIR alle
setGeneric(name = "getKIRGeneNames", def = function(kil, ...) {
  standardGeneric("getKIRGeneNames")
})

#' @keywords internal
#' Declare extractor to pull allele counts per gene
setGeneric(name = "getKIRAlleleCounts", def = function(kil, ...) {
  standardGeneric("getKIRAlleleCounts")
})
